### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by null15** [bonnie-dentinger/palia-fishing-ocr#1]
How does this work, and how do you use it? On console, it just says "running"

**Comment by bonbonbubbles** [comment]
I will be working on a tutorial tonight and updated instructions in the console! Unfortunately it looks as if there is a small problem with the latest release that's already fixed, just needs to be released. I'll let you know when it's up!

**Comment by bonbonbubbles** [comment]
This has been fixed now! please check out the latest release. Thank you :)

**Comment by null15** [comment]
Sweet! Just one curiosity, since theres no .exe now, I ran it using python in console, but I ran into no module of "screen_ocr", so I pip installed it, then it was pymongo. Then I ran into bunch of errors where I needed "screen-ocr[tesseract]". Now it says I don't have tesseract in sys var PATH, but I don't think I should download tesseract and add it to my sys var, unless I have to? I fear I'll get other errors anyway after going through that.

Any possibility you could pack the game into an executable? No need to assuming installing tesseract will fix the issue, but I'm not sure what that is and for what.🥲

**Comment by bonnie-dentinger** [comment]
oh lord please delete that. I'll fix this asap.

**Comment by bonbonbubbles** [comment]
.. I zipped the wrong files. please delete those!

**Comment by null15** [comment]
> .. I zipped the wrong files. please delete those!

No worries xD I deleted them, thought something was wrong since the folder name was differently as well.

**Comment by bonbonbubbles** [comment]
okay! It should be good now, you can download palia-fishing-ocr.zip and the exe is called palia-fishing-ocr.exe

Please let me know if this works any better for you and thank you so much for helping me out here :)

**Comment by null15** [comment]
Been using it for a while now, its working flawlessly! Great work bud. :)
